const card_names = {
    advance: `Advance`,
    basic_diagonal: `Basic Diagonal`,
    basic_orthogonal: `Basic Orthogonal`,
    basic_slice: `Basic Slice`,
    beam_diagonal: `Beam Diagonal`,
    beam_ne: `Beam NE`,
    beam_nw: `Beam NW`,
    beam_orthogonal: `Beam Orthogonal`,
    beam_se: `Beam SE`,
    beam_sw: `Beam SW`,
    bite: `Bite`,
    bounding_retreat: `Bounding Retreat`,
    branch_strike: `Branch Strike`,
    breakthrough_horizontal: `Breakthrough Horizontal`,
    breakthrough_vertical: `Breakthrough Vertical`,
    butterfly: `Butterfly`,
    charge_horizontal: `Charge Horizontal`,
    charge_vertical: `Charge Vertical`,
    chomp: `Chomp`,
    clear_behind: `Clear Behind`,
    clear_in_front: `Clear in Front`,
    combat_diagonal: `Combat Diagonal`,
    combat_orthogonal: `Combat Orthogonal`,
    dash_ne: `Dash NE`,
    dash_nw: `Dash NW`,
    debilitating_confusion: `Debilitating Confusion`,
    diamond_attack: `Diamond Attack`,
    diamond_slice: `Diamond Slice`,
    execution_1: `Execution 1`,
    execution_2: `Execution 2`,
    execution_3: `Execution 3`,
    explosion: `Explosion`,
    fangs: `Fangs`,
    firebreathing_horizontal: `Firebreathing Horizontal`,
    firebreathing_ne: `Firebreathing NE`,
    firebreathing_nw: `Firebreathing NW`,
    firebreathing_vertical: `Firebreathing Vertical`,
    flanking_diagonal: `Flanking Diagonal`,
    flanking_horizontal: `Flanking Horizontal`,
    flanking_vertical: `flanking Vertical`,
    force: `Force`,
    fork: `Fork`,
    freeze_up: `Freeze Up`,
    glide: `Glide`,
    hit_and_run: `Hit and Run`,
    horsemanship: ``,
    instant_teleport: `Instant Teleport`,
    jab_diagonal: `Jab Diagonal`,
    jab_orthogonal: `Jab Orthogonal`,
    jump: `Jump`,
    lash_out: `Lash Out`,
    leap_left: `Leap Left`,
    leap_right: `Leap Right`,
    lightheaded: `Lightheaded`,
    lost_maneuver: `Lost Maneuver`,
    lost_technique: `Lost Technique`,
    lunge_left: `Lunge Left`,
    lunge_right: `Lunge_right`,
    maneuver_1: `Maneuver 1`,
    maneuver_2: `Maneuver 2`,
    maneuver_3: `Maneuver 3`,
    overcome_horizontal: `Overcome Horizontal`,
    overcome_vertical: `Overcome Vertical`,
    pike: `Pike`,
    punch_diagonal: `Punch Diagonal`,
    punch_orthogonal: `Punch Orthogonal`,
    push_back: `Push Back`,
    reckless_attack_left: `Reckless Attack Left`,
    reckless_attack_right: `Reckless Attack Right`,
    reckless_leap_forwards: `Reckless Leap Forwards`,
    reckless_leap_left: `Reckless Leap Left`,
    reckless_leap_right: `Reckless Leap Right`,
    reckless_sidestep_diagonal: `Reckless Sidestep Diagonal`,
    reckless_sidestep_orthogonal: `Reckless Sidestep Orthogonal`,
    reckless_spin: `Reckless Spin`,
    reckless_sprint: `Reckless Sprint`,
    reckless_teleport: `Reckless Teleport`,
    regenerate: `Regenerate`,
    roll_horizontal: `Roll Horizontal`,
    roll_ne: `Roll NE`,
    roll_nw: `Roll NW`,
    saw_strike: `Saw Strike`,
    short_charge_diagonal: `Short Charge Diagonal`,
    short_charge_orthogonal: `Short Charge Orthogonal`,
    sidestep_e: `Sidestep E`,
    sidestep_n: `Sidestep N`,
    sidestep_ne: `Sidestep NE`,
    sidestep_nw: `Sidestep NW`,
    sidestep_s: `Sidestep S`,
    sidestep_se: `Sidestep SE`,
    sidestep_sw: `Sidestep SW`,
    sidestep_w: `Sidestep W`,
    skitter: `Skitter`,
    slash_step_forwards: `Slash Step Forwards`,
    slash_step_left: `Slash Step Left`,
    slash_step_right: `Slash step Right`,
    slice_twice: `Slice Twice`,
    slip_through_ne: `Slip Through NE`,
    slip_through_nw: `Slice Through NW`,
    slither: `Slither`,
    snack: `Snack`,
    soar: `Soar`,
    spearhead: `Spearhead`,
    spin_attack: `Spin Attack`,
    split_second_1: `Split Second 1`,
    split_second_2: `Split Second 2`,
    sprint_horizontal: `Sprint Horizontal`,
    sprint_vertical: `Sprint Vertical`,
    step_left: `Step Left`,
    step_right: `Step Right`,
    stumble_e: `Stumble E`,
    stumble_n: `Stumble N`,
    stumble_ne: `Stumble NE`,
    stumble_nw: `Stumble NW`,
    stumble_s: `Stumble S`,
    stumble_se: `Stumble SE`,
    stumble_sw: `Stumble SW`,
    stumble_w: `Stumble W`,
    stunning_leap_horizontal: `Stunning Leap Horizontal`,
    stunning_leap_vertical: `Stunning Leap Vertical`,
    stunning_punch_diagonal: `Stunning Punch Diagonal`,
    stunning_punch_orthogonal: `Stunning Punch Orthogonal`,
    stunning_retreat: `Stunning Retreat`,
    stunning_slice: `Stunning Slice`,
    stunning_tread_diagonal: `Stunning Tread Diagonal`,
    stunning_tread_orthogonal: `Stunning Tread Orthogonal`,
    superweapon_1: `Superweapon 1`,
    superweapon_2: `Superweapon 2`,
    symbol_add_card: `Add`,
    symbol_deck_at_minimum: `Minimum`,
    symbol_not_encountered_card: `Not Encountered`,
    symbol_remove_card: `Remove`,
    t_strike_horizontal: `T Strike Horizontal`,
    t_strike_vertical: `T Strike Vertical`,
    teleport: `Teleport`,
    thwack: `Thwack`,
    trample: `Trample`,
    trident: `Trident`,
    vine_snare: `Vine Snare`,
    y_leap: `Y Leap`,
    y_strike_ne: `Y Strike NE`,
    y_strike_nw: `Y Strike NW`,
}
Object.freeze(card_names);