function refresh_stage_stats(stats, location){
    display.remove_children(location);
    display.make_stat_pair(
        location,
        `${IMG_FOLDER.src}${IMG_FOLDER.stats}stairs.png`, 
        stats.floor, 
        stat_image_labels.floor
    );
    display.make_stat_pair(
        location,
        `${IMG_FOLDER.src}${IMG_FOLDER.stats}stopwatch.png`, 
        stats.turn, 
        stat_image_labels.turns
    );
    display.make_stat_pair(
        location,
        `${IMG_FOLDER.src}${IMG_FOLDER.stats}kills.png`, 
        stats.kills, 
        stat_image_labels.kills
    );
    display.make_stat_pair(
        location,
        `${IMG_FOLDER.src}${IMG_FOLDER.stats}damage_dealt.png`, 
        stats.dealt, 
        stat_image_labels.dealt
    );
    display.make_stat_pair(
        location,
        `${IMG_FOLDER.src}${IMG_FOLDER.stats}half_heart.png`, 
        stats.taken, 
        stat_image_labels.taken
    );
    display.make_stat_pair(
        location,
        `${IMG_FOLDER.src}${IMG_FOLDER.stats}mini_chest.png`, 
        stats.chests, 
        stat_image_labels.chests
    );
    display.make_stat_pair(
        location,
        `${IMG_FOLDER.src}${IMG_FOLDER.stats}mini_broken_chest.png`, 
        stats.destroyed, 
        stat_image_labels.destroyed
    );
}
function refresh_other_stats(stats, location){
    display.remove_children(location);
    display.make_stat_pair(
        location,
        `${IMG_FOLDER.src}${IMG_FOLDER.stats}stairs.png`, 
        stats.floor, 
        stat_image_labels.floor
    );
    display.make_stat_pair(
        location,
        `${IMG_FOLDER.src}${IMG_FOLDER.stats}stopwatch.png`, 
        stats.turn, 
        stat_image_labels.turns
    );
    display.make_stat_pair(
        location,
        `${IMG_FOLDER.src}${IMG_FOLDER.stats}mini_heart.png`, 
        stats.health, 
        stat_image_labels.health
    );
    display.make_stat_pair(
        location,
        `${IMG_FOLDER.src}${IMG_FOLDER.stats}card_added.png`, 
        stats.added, 
        stat_image_labels.added
    );
    display.make_stat_pair(
        location,
        `${IMG_FOLDER.src}${IMG_FOLDER.stats}card_removed.png`, 
        stats.removed, 
        stat_image_labels.removed
    );
}