const boon_names = {
    locked: `Locked`,
    not_encountered: `Not Encountered`,

    ancient_card: `Ancient Card I`,
    ancient_card_2: `Ancient Card II`,
    bitter_determination: `Bitter Determination`,
    blood_alchemy: `Blood Alchemy`,
    boss_slayer: `Boss Slayer`,
    brag_and_boast: `Brag & Boast`,
    burn_bright: `Burn Bright`,
    chilly_presence: `Chilly Presence`,
    choose_your_path: `Choose Your Path`,
    clairvoyance: `Clairvoyance`,
    clean_mind: `Clean Mind`,
    creative: `Creative`,
    dazing_blows: `Dazing Blows`,
    delayed_strike: `Delayed Strike`,
    duplicate: `Duplicate`,
    empty_rooms: `Empty Rooms`,
    escape_artist: `Escape Artist`,
    expend_vitality: `Expend Vitality`,
    flame_strike: `Flame Strike`,
    flame_worship: `Flame Worship`,
    fleeting_thoughts: `Fleeting Thoughts`,
    fortitude: `Fortitude`,
    frenzy: `Frenzy`,
    frugivore: `Frugivore`,
    grab_bag: `Grab Bag`,
    gruntwork: `Gruntwork`,
    hoarder: `Hoarder`,
    larger_chests: `Larger Chests`,
    limitless: `Limitless`,
    malicious_greeting: `Malicious Greeting`,
    manic_presence: `Manic Presence`,
    medical_investment: `Medical Investment`,
    pacifism: `Pacifism`,
    pain_reflexes: `Pain Reflexes`,
    pandoras_box: `Pandora's Box`,
    perfect_the_basics: `Perfect the Basics`,
    picky_shopper: `Picky Shopper`,
    practice_makes_perfect: `Practice Makes Perfect`,
    pressure_points: `Preassure Points`,
    rebirth: `Rebirth`,
    reckless_speed: `Reckless Speed`,
    repetition: `Repetition`,
    retaliate: `Retaliate`,
    rift_touched: `Rift Touched`,
    roar_of_challenge: `Roar of Challenge`,
    safe_passage: `Safe Passage`,
    shattered_glass: `Shattered Glass`,
    skill_trading: `Skill Trading`,
    slime_trail: `Slime Trail`,
    sniper: `Sniper`,
    soul_voucher: `Soul Voucher`,
    spiked_shoes: `Spiked Shoes`,
    spontaneous: `Spontaneous`,
    stable_mind: `Stable Mind`,
    stealthy: `Stealthy`,
    stubborn: `Stubborn`,
    thick_soles: `Thick Soles`,
    vicious_cycle: `Vicious Cycle`,
    world_shaper: `World Shaper`,
}
Object.freeze(boon_names);