const other_flavor = {
    altar_of_scouring:
        ``,
    altar_of_shadow:
        ``,
    altar_of_singularity:
        ``,
    altar_of_space:
        ``,
    altar_of_stars:
        ``,
    altar_of_stasis:
        ``,
    altar_of_sunlight:
        ``,
    black_hole:
        ``,
    bookshelf:
        ``,
    coffin:
        ``,
    corrosive_slime:
        ``,
    fireball:
        ``,
    fruit_tree_enticing:
        ``,
    fruit_tree_rotting:
        ``,
    lava_pool:
        ``,
    magmatic_boulder:
        ``,
    moon_rock:
        ``,
    raging_fire:
        ``,
    repulsor:
        ``,
    sewer_grate:
        ``,
    shatter_sphere:
        ``,
    smoldering_ashes:
        ``,
    thorn_bramble:
        ``,
    wall:
        ``,
    wall_damaged:
        ``,
}
Object.freeze(other_flavor);