const enemy_names = {
    acid_bug: `Acid Bug`, 
    animated_boulder: `Animated Boulder`, 
    blood_crescent: `Blood Crescent`,
    brightling: `Brightling`, 
    captive_void: `Captive Void`, 
    carrion_flies: `Carrion Flies`, 
    claustropede_1: `Claustropede x1`,
    claustropede_2: `Claustropede x2`,
    claustropede_3: `Claustropede x4`,
    clay_golem: `Clay Golem`, 
    corrosive_caterpillar: `Corrosive Caterpillar`, 
    darkling: `Darkling`, 
    gem_crawler: `Gem Crawler`, 
    igneous_crab: `Igneous Crab`, 
    living_tree: `Living Tree`, 
    magma_spewer: `Magma Spewer`, 
    maw: `Maw`,
    noxious_toad: `Noxious Toad`, 
    orb_of_insanity: `Orb of Insanity`, 
    paper_construct: `Paper Construct`, 
    pheonix: `Pheonix`, 
    porcuslime_large: `Large Porcuslime`, 
    porcuslime_medium: `Medium Porcuslime`, 
    porcuslime_small: `Small Porcuslime`, 
    ram: `Ram`, 
    rat: `Rat`, 
    scorpion: `Scorpion`, 
    scythe: `Scythe`, 
    shadow_knight: `Shadow Knight`, 
    shadow_knight_elite: `Shadow Knight Elite`, 
    shadow_scout: `Shadow Scout`, 
    specter: `Specter`, 
    spider_web: `Spider Web`, 
    spider: `Spider`, 
    starcaller: `Starcaller`,
    strider: `Strider`, 
    swaying_nettle: `Swaying Nettle`, 
    thorn_bush: `Thorn Bush`, 
    turret: `Turret`, 
    turret_m: `Moving Turret`, 
    turret_r: `Rotary Turret`, 
    unspeakable: `Unspeakable`,
    unstable_wisp: `Unstable Wisp`, 
    vampire: `Vampire`, 
    vinesnare_bush: `Vinesnare Bush`, 
    walking_prism: `Walking Prism`,
    wheel_of_fire: `Wheel of Fire`,
}
Object.freeze(enemy_names);